### ISSUE TITLE
Request to update file-path with file-name in the *config.json, *profileInstances.yaml, *profiles.yaml

### ISSUE THREAD

**Issue by sunil-kumar-meena** [openBackhaul/MicroWaveDeviceGatekeeper#10]
**Problem Description:**
As per specification MicroWaveDeviceGatekeeper.yaml file-profile-configuration schema has file-name  
But in the *profileInstances.yaml, *profiles.yaml & *config.json the file-profile is present as mentioned below where the file profile configuration contains the property name as file-path instead of file-name,

```
- profile-name: 'FileProfile'
    uuid: '^[a-z]{2,6}-([0-9]+)-([0-9]+)-([0-9]+)-file-p-[0-9]{3}$'
    capability:
      file-identifier: string
      file-description: string
    configuration:
      file-path: string
      user-name: string
      password: string
      operation: string
```

```
{
  "uuid": "mwdg-1-0-0-file-p-000",
  "profile-name": "file-profile-1-0:PROFILE_NAME_TYPE_FILE_PROFILE",
  "file-profile-1-0:file-profile-pac": {
    "file-profile-capability": {
      "file-identifier": "EncryptedOdlKey",
      "file-description": "Authorization key for OpenDayLight"
    },
    "file-profile-configuration": {
      "file-path": "../application-data/encrypted-odl-key.json",
      "user-name": "MicroWaveDeviceGatekeeper",
      "password": "Operations to add password",
      "operation": "file-profile-1-0:OPERATION_TYPE_READ_ONLY"
    }
  }
}
```

As per the decision in the issue  https://github.com/openBackhaul/ApplicationPattern/issues/646  the attribute file-path will be replaced by file-name

**Proposal :**
1. Replacing the attribute file-path with file-name
2. Replacing the value of the attribute from "../application-data/encrypted-odl-key.json" to "encrypted-odl-key.json"
