### ISSUE TITLE
To remove unused component uuid1 

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/MicroWaveDeviceGatekeeper#12]
In the OAS , the defined uuid1 component shall be removed as it is nowhere used
```
uuid1:
      name: uuid1
      in: path
      required: true
      schema:
        type: string
        example: 'LTP-MWPS-TTP-1-1'
      description: 'Another instance identifier that is unique within the device'
```

> Note : There is no harm in having this entity. Included this issue to remove the unused code
