### ISSUE TITLE
To ignore "server" folder in the .github/workflows/yaml-lint.yaml rules

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/MicroWaveDeviceGatekeeper#37]
To ignore the ./server/api/openapi.yaml file from the yaml-lint validation , rules in the .github/workflows/yaml-lint.yaml shall be modified to ignore the folder server.
```yaml
ignore: |
   server/
```

**Comment by openBackhaul** [comment]
Could you please check, whether the change has the wished effect.
If yes, please close the issue.
If not, please assign back to me an send email to indicate need for change.

````
name: Yaml Lint
on:
  pull_request:
    branches: [develop]
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          format: github
          config_data: |
            extends: default
            ignore: |
              /server/
            rules:
              line-length: disable
              document-start: disable
````
